package io.mec.edge.controller.tariff;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "MEC Controller Tariff", //
		description = "Time-of-Use tariff provider that publishes DISCOM rate schedules as OpenEMS TimeOfUsePrices.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlTariff0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "State",
			description = "State identifier used to select the bundled or external YAML tariff file (e.g. 'karnataka', 'punjab').")
	String state() default "karnataka";

	@AttributeDefinition(name = "Tariff Config Directory",
			description = "Filesystem directory to check for an external tariff YAML before falling back to the bundled resource.")
	String tariffConfigDir() default "/etc/mec/tariff";

	@AttributeDefinition(name = "Meter-ID", description = "ID of the electricity meter used for peak demand tracking.")
	String meter_id() default "meter0";

	@AttributeDefinition(name = "Meter target filter", description = "This is auto-generated by 'Meter-ID'.")
	String meter_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "MEC Controller Tariff [{id}] [{state}]";
}
