package io.mec.edge.controller.loadintelligence;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "MEC Controller Load Intelligence", //
		description = "CT-sensor-based load classification and EMS-controlled load shedding with inrush guard.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ctrlLoadIntelligence0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Battery-ID", description = "ID of the Battery device.")
	String battery_id();

	@AttributeDefinition(name = "Battery target filter", description = "This is auto-generated by 'Battery-ID'.")
	String battery_target() default "(enabled=true)";

	@AttributeDefinition(name = "Site-ID", description = "Logical site identifier used for logging and telemetry.")
	String site_id() default "site0";

	@AttributeDefinition(name = "Load Config Directory",
			description = "Filesystem path to the directory containing the load YAML configuration file.")
	String loadConfigDir() default "/etc/mec/loads";

	@AttributeDefinition(name = "Shed Threshold SoC",
			description = "Battery SoC fraction [0.0–1.0] at or below which all NON_CRITICAL loads are shed.")
	double shedThresholdSoc() default 0.20;

	@AttributeDefinition(name = "Restore Threshold SoC",
			description = "Battery SoC fraction [0.0–1.0] at or above which shed loads begin restoration.")
	double restoreThresholdSoc() default 0.35;

	@AttributeDefinition(name = "Inter-Restore Delay (seconds)",
			description = "Minimum time in seconds to wait between successive load restore events.")
	int interRestoreDelaySeconds() default 30;

	@AttributeDefinition(name = "Max Site Inrush (A)",
			description = "Maximum allowable estimated inrush current in amperes for a single restore event.")
	double maxSiteInrushAmps() default 200.0;

	@AttributeDefinition(name = "Nominal Voltage (V)",
			description = "Nominal phase-to-neutral voltage used for power calculation (V).")
	double nominalVoltageV() default 230.0;

	String webconsole_configurationFactory_nameHint() default "MEC Controller Load Intelligence [{id}]";
}
