package io.mec.edge.controller.degradation;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

/**
 * OSGi ConfigAdmin interface for the MEC Degradation Controller.
 */
@ObjectClassDefinition(//
		name = "MEC Controller Degradation", //
		description = "LFP battery SoH model and marginal degradation cost per kWh dispatched")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "mecDegradation0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	// ---- Battery reference ----

	@AttributeDefinition(name = "Battery-ID", description = "ID of the Battery component")
	String battery_id() default "battery0";

	@AttributeDefinition(name = "Battery target filter", description = "Auto-generated by Battery-ID")
	String battery_target() default "(enabled=true)";

	// ---- Chemistry constants (LFP defaults) ----

	@AttributeDefinition(name = "Arrhenius A (fade/day)", //
			description = "Pre-exponential frequency factor. Default: LFP 1.4e-3")
	double arrheniusA() default 1.4e-3;

	@AttributeDefinition(name = "Arrhenius Ea (eV)", //
			description = "Activation energy in electron-volts. Default: LFP 0.60 eV")
	double arrheniusEaEv() default 0.60;

	// ---- BESS sizing ----

	@AttributeDefinition(name = "Nameplate capacity (kWh)")
	double nameplateKwh() default 200.0;

	@AttributeDefinition(name = "Replacement cost (INR)")
	double replacementCostInr() default 7_000_000.0;

	// ---- Calendar tracking ----

	@AttributeDefinition(name = "Commission date (ISO-8601)", //
			description = "Date battery was commissioned, e.g. 2024-01-15")
	String commissionDate() default "2024-01-15";

	// ---- Persisted aging state (written back by controller on each cycle) ----

	@AttributeDefinition(name = "Persisted calendar fade (0–1)", //
			description = "Cumulative calendar capacity fade — restored on restart")
	double persistedCalendarFade() default 0.0;

	@AttributeDefinition(name = "Persisted EFC", //
			description = "Equivalent full cycle count — restored on restart")
	double persistedEfc() default 0.0;

	String webconsole_configurationFactory_nameHint() default "MEC Controller Degradation [{id}]";
}
